POST /api/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email": "vinod@vinod.co",
    "password": "topsecret"
}

### invalid email/password

POST /api/login
Host: localhost:8080
Content-Type: application/json

{
    "email": "vinod@sapient",
    "password": "topsecret"
}

###
GET /api/orders
Host: localhost:8080

###
GET /api/orders
Host: localhost:8080
Accept: application/json
Authorization: asdasdasd


###
GET /api/orders
Host: localhost:8080
Accept: application/json
Authorization: asda sdasd.asd.asd

### expired token
GET /api/orders
Host: localhost:8080
Accept: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJWaW5vZCBLdW1hciBLYXlhcnRheWEiLCJpZCI6MTIzNCwiZXhwIjoxNjIwNDU0OTc3LCJpYXQiOjE2MjA0NTQwNzd9.yc3i3lre-AUyNB_CkQ1pB9x2ZeFFE_CtJt0JM0MZy4Y

###
GET /api/orders
Host: localhost:8080
Accept: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJWaW5vZCBLdW1hciBLYXlhcnRheWEiLCJpZCI6MTIzNCwiZXhwIjoxNjIyOTc5MzI3LCJpYXQiOjE2MjI5Nzg0Mjd9.ZyjoeZ8_xgQAcilJIb27qV1vI4MFWtz4_vJoT8g27kI

### TAMPERED JWT TOKEN
GET /api/orders
Host: localhost:8080
Accept: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJWaW5vZCBLdW1hciBLYXlhcnRheWEiLCJpZCI6Nzg5MCwiZXhwIjoxNjIwNTUyNzY1LCJpYXQiOjE2MjA1NTE4NjV9.4iDIeV4z3C1InYBNfhPD1K8yTnvbr7g_Xp0L90BbJjA


####

http://localhost:8080/api/products
###

http://localhost:8080/api/products/22