package co.vinod.programs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class GetAutoGeneratedPrimaryKeyValue {
	
	public static void main(String[] args) throws Exception{
		
		String url = "jdbc:mysql://localhost/batch5";
		String username = "root";
		String password = "Welcome#123";
		
		Connection conn = DriverManager.getConnection(url, username, password);
		String sql = "insert into products values (null, ?,?,?,?,?,?,?,?)";
		PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
		
		stmt.setString(1, "vegitable");
		stmt.setString(2, "Cabbage Organic");
		stmt.setString(3, "Zespri");
		stmt.setString(4, "Cabbage - Red organically grown");
		stmt.setString(5, "1 pc approx 500gm");
		stmt.setDouble(6, 75);
		stmt.setString(7, "http://kvinod.com/resources/product-images/10000171_11-fresho-cabbage-red.jpg");
		stmt.setDouble(8, 2);

		stmt.executeUpdate();
				
		ResultSet keys = stmt.getGeneratedKeys();
		if(keys.next()) {
			System.out.println("Generated primary key value is " + keys.getInt(1));
		}
		
		keys.close();
		stmt.close();
		conn.close();
	}

}
